# Standalone host regression tests.  This does not run any R5900 assembly.
CC ?= cc
CFLAGS ?= -O2 -std=c99 -Wall -Wextra -Werror

.PHONY: all test clean
all: test

ps2/test_rgb3_host: ps2/test_rgb3_host.c ps2/filter_rgb3.c
	$(CC) $(CFLAGS) ps2/test_rgb3_host.c -o $@

ps2/test_mmi_models: ps2/test_mmi_models.c
	$(CC) $(CFLAGS) ps2/test_mmi_models.c -o $@

test: ps2/test_rgb3_host ps2/test_mmi_models
	./ps2/test_rgb3_host
	./ps2/test_mmi_models

clean:
	$(RM) ps2/test_rgb3_host ps2/test_mmi_models
